export const COMPANIES_LOAD_IN_PROGRESS = 'COMPANIES_LOAD_IN_PROGRESS'
export const COMPANIES_LOAD_COMPLETED = 'COMPANIES_LOAD_COMPLETED'
export const COMPANIES_LOAD_ERROR = 'COMPANIES_LOAD_ERROR'
export const COMPANIES_CHANGED = 'COMPANIES_CHANGED'
export const COMPANIES_LOAD_MORE = 'COMPANIES_LOAD_MORE'


export const OPEN_QUESTIONS = 'OPEN_QUESTIONS'
export const QUESTIONS_LOAD_IN_PROGRESS = 'QUESTIONS_LOAD_IN_PROGRESS'
export const QUESTIONS_LOAD_ERROR = 'QUESTIONS_LOAD_ERROR'
export const QUESTIONS_LOAD_COMPLETED = 'QUESTIONS_LOAD_COMPLETED'
export const QUESTION_DETAILS = 'QUESTION_DETAILS'
