export const COMPANIES_LOAD_IN_PROGRESS = 'COMPANIES_LOAD_IN_PROGRESS'
export const COMPANIES_LOAD_COMPLETED = 'COMPANIES_LOAD_COMPLETED'
export const COMPANIES_LOAD_ERROR = 'COMPANIES_LOAD_ERROR'
export const COMPANIES_CHANGED = 'COMPANIES_CHANGED'
export const COMPANIES_LOAD_MORE = 'COMPANIES_LOAD_MORE'


export const OPEN_QUESTIONS = 'OPEN_QUESTIONS'
export const QUESTIONS_LOAD_IN_PROGRESS = 'QUESTIONS_LOAD_IN_PROGRESS'
export const QUESTIONS_LOAD_ERROR = 'QUESTIONS_LOAD_ERROR'
export const QUESTIONS_LOAD_COMPLETED = 'QUESTIONS_LOAD_COMPLETED'

export const OPEN_QUESTION_DETAIL = 'OPEN_QUESTION_DETAIL'
export const QUESTIONS_DETAIL_LOAD_IN_PROGRESS = 'QUESTIONS_DETAIL_LOAD_IN_PROGRESS'
export const QUESTIONS_DETAIL_LOAD_ERROR = 'QUESTIONS_DETAIL_LOAD_ERROR'
export const QUESTIONS_DETAIL_LOAD_COMPLETED = 'QUESTIONS_DETAIL_LOAD_COMPLETED'

export const BOOKMARK_QUESTIONS_ADD = 'BOOKMARK_QUESTIONS_ADD'
export const BOOKMARK_QUESTIONS_REMOVE = 'BOOKMARK_QUESTIONS_REMOVE'
export const BOOKMARK_QUESTIONS_LOAD_IN_PROGRESS = 'BOOKMARK_QUESTIONS_LOAD_IN_PROGRESS'
export const BOOKMARK_QUESTIONS_DETAIL_LOAD_ERROR = 'BOOKMARK_QUESTIONS_DETAIL_LOAD_ERROR'
export const BOOKMARK_QUESTIONS_DETAIL_LOAD_COMPLETED = 'BOOKMARK_QUESTIONS_DETAIL_LOAD_COMPLETED'
